name = "Allison and Nick's Survival"
author = "salviija"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54dc45700d100e329d4183bad63f4da181b236beace430417c89458af3e8ea56"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
