name = "Allison and Nick's Survival"
author = "salviija"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5b9317f1811350d91a89ede896ce2ff85a4a98c48d195b8115dfb69cdaf21ba"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
