name = "alicemoddedsurvival"
author = "salviija"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22fd8d96f87b7a76647afda751920445bae981779e18b1341cd3b9de00fe897f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
